# Implementing Neural Network from Scratch :

* Needed Libraries :

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
from sklearn.preprocessing import StandardScaler

* Defining Activitation function :

In [ ]:
# Activation function (sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
# Derivative of sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

* Implementing Neurak Network Netwok from scratch using Sigmoid as an activitation function :

In [ ]:
# Neural Network class
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        # Initialize weights and biases
        self.weights_input_hidden = np.random.rand(self.input_size, self.hidden_size)
        self.bias_hidden = np.zeros((1, self.hidden_size))
        self.weights_hidden_output = np.random.rand(self.hidden_size, self.output_size)
        self.bias_output = np.zeros((1, self.output_size))
#####################################################################################################################
    def feedforward(self, X):
        # Input to hidden layer
        self.hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = sigmoid(self.hidden_input)
        # Hidden to output layer
        self.output_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        self.predicted_output = sigmoid(self.output_input)

        return self.predicted_output
#####################################################################################################################\
    def backpropagation(self, X, y, learning_rate):
        # Calculate error
        output_error = y-self.predicted_output
        # Output layer gradient
        output_delta = output_error* sigmoid_derivative(self.predicted_output)
        # Hidden layer error
        hidden_error = output_delta.dot(self.weights_hidden_output.T)
        # Hidden layer gradient
        hidden_delta = hidden_error*sigmoid_derivative(self.hidden_output)
        # Update weights and biases
        self.weights_hidden_output += self.hidden_output.T.dot(output_delta) * learning_rate

        self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
        self.weights_input_hidden += X.T.dot(hidden_delta) * learning_rate
        self.bias_hidden += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate
#####################################################################################################################
    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            predicted_output = self.feedforward(X)
            self.backpropagation(X, y, learning_rate)
#####################################################################################################################
    def test(self, X_test):
        return np.round(self.feedforward(X_test))

* Datasets Description :

In [ ]:
# Load Iris dataset
iris = load_iris()
X_iris = iris.data
y_iris = pd.get_dummies(iris.target).values
#####################################################################################################################
# Display statistical description for IRIS dataset
print("Statistical Description of IRIS dataset:")
print(pd.DataFrame(X_iris, columns=iris.feature_names).describe())
#####################################################################################################################
# Display information about IRIS dataset
print("Information about IRIS dataset:")
print(pd.DataFrame(X_iris, columns=iris.feature_names).info())
#####################################################################################################################
# Load MNIST dataset
digits = load_digits()
X_mnist = StandardScaler().fit_transform(digits.data)
y_mnist = pd.get_dummies(digits.target).values
#####################################################################################################################
# Display statistical description for MNIST dataset
print("Statistical Description of MNIST dataset:")
print(pd.DataFrame(X_mnist, columns=[f"pixel_{i}" for i in range(X_mnist.shape[1])]).describe())
#####################################################################################################################
# Display information about MNIST dataset
print("Information about MNIST dataset:")
print(pd.DataFrame(X_mnist, columns=[f"pixel_{i}" for i in range(X_mnist.shape[1])]).info())

Statistical Description of IRIS dataset:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  
Information about IRIS dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 # 

* Applying the Neural newtwork and printing the results :

In [ ]:
# The results using Sigmoid as an activitation function
# Load IRIS dataset
iris = load_iris()
X_iris = iris.data
y_iris = pd.get_dummies(iris.target).values
#####################################################################################################################
# Split the dataset into trai#ning and testing sets
X_iris_train, X_iris_test, y_iris_train, y_iris_test = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)
#####################################################################################################################
# Initialize and train the neural network for IRIS dataset
input_size_iris = X_iris.shape[1]
hidden_size_iris = 10
output_size_iris = y_iris.shape[1]
epochs_iris = 1000
learning_rate_iris = 0.01
#####################################################################################################################
nn_iris = NeuralNetwork(input_size_iris, hidden_size_iris, output_size_iris)
nn_iris.train(X_iris_train, y_iris_train, epochs_iris, learning_rate_iris)
#####################################################################################################################
# Test the model on IRIS dataset
y_iris_pred = nn_iris.test(X_iris_test)
conf_matrix_iris = confusion_matrix(np.argmax(y_iris_test, axis=1), np.argmax(y_iris_pred, axis=1))
accuracy_iris = accuracy_score(np.argmax(y_iris_test, axis=1), np.argmax(y_iris_pred, axis=1)) * 100
#####################################################################################################################
print("Confusion Matrix (IRIS):")
print(conf_matrix_iris)
print("Accuracy (IRIS): {:.2f}%".format(accuracy_iris))
#####################################################################################################################
# Load MNIST dataset
digits = load_digits()
X_mnist = StandardScaler().fit_transform(digits.data)
y_mnist = pd.get_dummies(digits.target).values
#####################################################################################################################
# Split the dataset into training and testing sets
X_mnist_train, X_mnist_test, y_mnist_train, y_mnist_test = train_test_split(X_mnist, y_mnist, test_size=0.2, random_state=42)
#####################################################################################################################
# Initialize and train the neural network for MNIST dataset
input_size_mnist = X_mnist.shape[1]
hidden_size_mnist = 88
output_size_mnist = y_mnist.shape[1]
epochs_mnist = 1000
learning_rate_mnist = 0.01
#####################################################################################################################
nn_mnist = NeuralNetwork(input_size_mnist, hidden_size_mnist, output_size_mnist)
nn_mnist.train(X_mnist_train, y_mnist_train, epochs_mnist, learning_rate_mnist)
#####################################################################################################################
# Test the model on MNIST dataset
y_mnist_pred = nn_mnist.test(X_mnist_test)
conf_matrix_mnist = confusion_matrix(np.argmax(y_mnist_test, axis=1), np.argmax(y_mnist_pred, axis=1))
accuracy_mnist = accuracy_score(np.argmax(y_mnist_test, axis=1), np.argmax(y_mnist_pred, axis=1)) * 100
#####################################################################################################################
print("\nConfusion Matrix (MNIST):")
print(conf_matrix_mnist)
print("Accuracy (MNIST): {:.2f}%".format(accuracy_mnist))


Confusion Matrix (IRIS):
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy (IRIS): 100.00%

Confusion Matrix (MNIST):
[[33  0  0  0  0  0  0  0  0  0]
 [ 1 27  0  0  0  0  0  0  0  0]
 [ 0  1 31  1  0  0  0  0  0  0]
 [ 0  0  1 32  0  1  0  0  0  0]
 [46  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0 44  1  0  0  1]
 [ 1  0  0  0  0  0 34  0  0  0]
 [ 1  0  0  0  0  0  0 32  0  1]
 [ 4  2  0  0  0  1  0  0 23  0]
 [ 2  0  0  1  0  2  0  0  2 33]]
Accuracy (MNIST): 80.28%
